### ISSUE TITLE
提示完下载信息后就没动静了

### ISSUE THREAD

**Issue by Kuwaaaa** [erzaozi/sunoai-plugin#6]
[MiaoYz][15:54:49.087][INFO] 还未生成好...
[MiaoYz][15:54:54.868][INFO] 还未生成好...
[MiaoYz][15:55:00.514][INFO] 还未生成好...
[MiaoYz][15:55:06.908][INFO] succeed to send: [Group(***)] [回复@***]生成歌曲成功，正在下载...
[MiaoYz][15:55:06.910][INFO] 信息已下载
[MiaoYz][15:55:06.913][INFO] 信息已下载

**Comment by CikeyQi** [comment]
配置文件仅选择了下载元数据吧？没选择下载音频和视频
